server:
  port: 8090
spring:
  profiles:
    include:
      - secret
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/arsleather?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # JSP 관련 설정 추가
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    # HiddenHttpMethodFilter 설정
    # HTML form은 GET과 POST만 지원하므로, PUT, PATCH, DELETE 등의 메소드를 사용하기 위해
    # X-HTTP-Method-Override 헤더를 통해 실제 메소드를 지정할 수 있게 해주는 필터
    hiddenmethod:
      filter:
        enabled: true
  # 정적 리소스 설정 추가
  web:
    resources:
      static-locations: classpath:/webapp/static/,file:///D:/kmw/upload/
file:
  upload:
    path: ./upload/
logging:
  level:
    root: INFO
    com.groo.kmw: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc: INFO
    org.springframework.transaction: INFO
    org.springframework.web: INFO
